packages:
  - "."
  - "utils/tsconfig"
  - "utils/prettier-config"
  - "utils/eslint-config"
  - "utils/rollup-utils"
  - "utils/cryptographer"
  - "utils/rollup-cryptospec"
  - "utils/rollup-obfuscator"
  - "utils/rollup-config"

  #- "packages/clients/atom"
  #- "!packages/clients/atom/package/*"

  #- "packages/prettify"

  #- "packages/clients/vscode"
  #- "!packages/clients/vscode/package/*"

  #- "packages/parser"

  #- "packages/server"
  #- "!packages/server/package/*"

  #- "packages/schema"
  #- "packages/specs"
  #- "web"
