packages:
  - "."
  - "build/*"
  - "build/rollup-plugins/*"
  - "!build/path-resolve/test/**"
  - "packages/*"
  - "packages/clients/*"
  - "!packages/server/package/*"
  - "!packages/clients/vscode/package/*"
  - "web/*"
