packages:
  - "."
  - "utils/tsconfig"
  - "utils/prettier-config"
  - "utils/eslint-config"
  - "utils/rollup-utils"
  - "utils/cryptographer"
  - "utils/rollup-plugins/rollup-cryptospec"
  - "utils/rollup-plugins/rollup-enums"
  - "utils/rollup-plugins/rollup-watch"
  - "utils/rollup-plugins/rollup-obfuscator"
  - "utils/rollup-config"
  - "packages/prettify"
  - "packages/schema"
  - "packages/specs"
  - "packages/parser"
  - "packages/server"
  - "editors/vscode"

