packages:
  - "."

  - "build/cryptographer"

  - "build/rollup-plugins/cryptospec"
  - "build/rollup-plugins/globs"
  - "build/rollup-plugins/obfuscator"
  - "build/rollup-plugins/utils"

  - "packages/clients/atom"
  - "!packages/clients/atom/package/*"

  - "packages/clients/vscode"
  - "!packages/clients/vscode/package/*"

  - "packages/parser"

  - "packages/server"
  - "!packages/server/package/*"

  - "packages/schema"
  - "packages/specs"
