packages:
  - "."

  - "build/rollup-plugins/utils"

  - "build/eslint-config"
  - "build/eslint-ts"
  - "build/eslint-js"

  - "build/cryptographer"
  - "build/rollup-plugins/cryptospec"

  - "build/rollup-plugins/globs"
  - "build/rollup-plugins/obfuscator"

  - "packages/clients/atom"
  - "!packages/clients/atom/package/*"

  - "packages/clients/vscode"
  - "!packages/clients/vscode/package/*"

  - "packages/parser"

  - "packages/server"
  - "!packages/server/package/*"

  - "packages/schema"
  - "packages/specs"
  - "web"
